from flask import Flask,request,jsonify
import pickle
import numpy as np

# model = pickle.load(open("model1.pkl","rb"))
model = pickle.load(open('model.pkl', 'rb'))

app = Flask(__name__)

@app.route('/')
def home():
    return "Hello world"

@app.route('/predict',methods=['POST'])
def predict():
    Fever = request.form.get("Fever")
    Headache = request.form.get("Headache")
    Fatigue = request.form.get("Fatigue")
    Cough = request.form.get("Cough")
    Bodyaches = request.form.get("Bodyaches")
    Sorethroat = request.form.get("Sorethroat")
    Runnynose = request.form.get("Runnynose")
    Nausea = request.form.get("Nausea")
    Vomiting = request.form.get("Vomiting")
    Diarrhea = request.form.get("Diarrhea")
    Toothache = request.form.get("Toothache")
    SensitiveTeeth = request.form.get("SensitiveTeeth")
    Mouthsore = request.form.get("Mouthsore")
    BrokenTeeth = request.form.get("BrokenTeeth")
    DiscoloredTeeth = request.form.get("DiscoloredTeeth")
    JawPain = request.form.get("JawPain")
    bloodinurine = request.form.get("bloodinurine")
    peeingproblem = request.form.get("peeingproblem")
    strongflowofurine = request.form.get("strongflowofurine")
    Changesinurination = request.form.get("Changesinurination")
    erection = request.form.get("erection")
    Urinating = request.form.get("Urinating")
    Numbness = request.form.get("Numbness")
    MusclePain = request.form.get("MusclePain")
    Weakness = request.form.get("Weakness")
    JointPain = request.form.get("JointPain")
    warmth = request.form.get("warmth")
    Stiffness = request.form.get("Stiffness")
    Swelling = request.form.get("Swelling")
    Surgery = request.form.get("Surgery")
    Exhaustion = request.form.get("Exhaustion")
    Depersonalization = request.form.get("Depersonalization")
    Lackefficacy = request.form.get("Lackefficacy")
    Sneezing = request.form.get("Sneezing")
    EarPain = request.form.get("EarPain")
    HearingLoss = request.form.get("HearingLoss")
    Snoring = request.form.get("Snoring")
    SleepApnea = request.form.get("SleepApnea")
    MouthBreathingissue = request.form.get("MouthBreathingissue")
    Chronicorsevereheadaches = request.form.get("Chronicorsevereheadaches")
    Dizziness = request.form.get("Dizziness")
    MovemnetProblems = request.form.get("MovemnetProblems")
    MemoryProblem = request.form.get("MemoryProblem")
    Eyepain = request.form.get("Eyepain")
    Redanditchyeyes = request.form.get("Redanditchyeyes")
    Blurryvision = request.form.get("Blurryvision")
    Highbloodpressure = request.form.get("Highbloodpressure")
    Chestpain = request.form.get("Chestpain")
    shortnessofbreath = request.form.get("shortnessofbreath")
    Highcholestrol = request.form.get("Highcholestrol")
    Frequentnigtmares = request.form.get("Frequentnigtmares")
    Anxiety = request.form.get("Anxiety")
    Physicalillness = request.form.get("Physicalillness")
    Inabilitytocontrolemotions = request.form.get("Inabilitytocontrolemotions")
    Rectalbleeding = request.form.get("Rectalbleeding")
    Abdominalpain = request.form.get("Abdominalpain")
    Heartburn = request.form.get("Heartburn")
    Bloodinstool = request.form.get("Bloodinstool")
    Constipation = request.form.get("Constipation")
    Asthma = request.form.get("Asthma")
    chronicbronchitis = request.form.get("chronicbronchitis")
    wheezing = request.form.get("wheezing")
    Dryskin = request.form.get("Dryskin")
    Urinatealot = request.form.get("Urinatealot")
    weightloss = request.form.get("weightloss")
    tiredness = request.form.get("tiredness")
    skincancer = request.form.get("skincancer")
    Rash = request.form.get("Rash")
    Scars = request.form.get("Scars")
    Hives = request.form.get("Hives")
    Acne = request.form.get("Acne")
    Pelvicpain = request.form.get("Pelvicpain")
    Urinaryissues = request.form.get("Urinaryissues")
    Vaginalbleeding = request.form.get("Vaginalbleeding")
    Breastpain = request.form.get("Breastpain")
    Painfulperiods = request.form.get("Painfulperiods")
    Feelingcold = request.form.get("Feelingcold")
    Hotflashes = request.form.get("Hotflashes")
    Growthretardation = request.form.get("Growthretardation")
    Delayedmilestones = request.form.get("Delayedmilestones")
    Lethargic = request.form.get("Lethargic")

    #Symptom_1 = request.form.get("Symptom_1")
    #Symptom_2 = request.form.get("Symptom_2")
    #Symptom_3 = request.form.get("Symptom_3")

    input_query = np.array([[Fever	,Headache	,Fatigue	,Cough,	Bodyaches	,Sorethroat	,Runnynose	,Nausea	,Vomiting	,Diarrhea	,Toothache	,SensitiveTeeth	,Mouthsore	,BrokenTeeth	,DiscoloredTeeth	,JawPain	,bloodinurine	,peeingproblem	,strongflowofurine	,Changesinurination	,erection	,Urinating	,Numbness	,MusclePain,	Weakness	,JointPain	,warmth	,Stiffness	,Swelling	,Surgery	,Exhaustion	,Depersonalization	,Lackefficacy	,Sneezing	,EarPain	,HearingLoss	,Snoring	,SleepApnea	,MouthBreathingissue	,Chronicorsevereheadaches	,Dizziness	,MovemnetProblems	,MemoryProblem	,Eyepain	,Redanditchyeyes	,Blurryvision	,Highbloodpressure	,Chestpain	,shortnessofbreath	,Highcholestrol	,Frequentnigtmares	,Anxiety	,Physicalillness	,Inabilitytocontrolemotions	,Rectalbleeding	,Abdominalpain	,Heartburn	,Bloodinstool	,Constipation	,Asthma	,chronicbronchitis	,wheezing	,Dryskin	,Urinatealot	,weightloss	,tiredness	,skincancer	,Rash	,Scars	,Hives	,Acne	,Pelvicpain	,Urinaryissues	,Vaginalbleeding	,Breastpain	,Painfulperiods,	Feelingcold	,Hotflashes	,Growthretardation	,Delayedmilestones	,Lethargic]])
   #input_query = np.array([[Symptom_1,Symptom_2,Symptom_3]])

    result = model.predict(input_query)[0]

    return jsonify(result)

if __name__ == '__main__':
    app.run(debug=True)